### ISSUE TITLE
wifi downlaod speed from local area network 

### ISSUE THREAD

**Issue by jack338c** [Krissh-C/T490-macOS#12]
the speed  of wilfi around 4/ms max while copying file from local area network  
is this normal ?

thanks

**Comment by ducks-c** [comment]
Haven't really copied any files over the network locally but I would say that depends mostly on your WiFi speeds. Did you mean 4mb/s? Because that's really slow.

There is an issue present with the airportitlwm kext that reduces the WiFi speed by a little bit. Basically the WiFi card does not reach its expected speeds. That could be why. 

This has been an issue for a while and I doubt it'll be fixed. You could try updating the kext with the latest release of the airportitlwm kext (released on 8 February as of writing) and see if that fixes it for you.

**Comment by jack338c** [comment]
Thank you for your fast response
after update the latest airportitlwm kext,the speed now is about 60M/s
have a nice day! 🥂
